// @ts-check
import { defineConfig } from 'astro/config';
import { unified } from '@astrojs/markdown-remark';
import node from '@astrojs/node';

// Astro only exposes .env to app code (import.meta.env), not to this file —
// load it into process.env ourselves so SITE/BASE/SSR below can come from it.
// Requires Node >=20.6; optional, so a missing .env is fine (defaults apply).
try {
	process.loadEnvFile();
} catch {
	// no .env file present — defaults below apply
}

// SSR=1 enables the Node adapter, the /new (create article) route, and an
// on-demand /wiki/[slug] route that generates missing articles with an LLM.
// Without it, this is a plain static build: no server, no OpenAI calls.
const ssr = process.env.SSR === '1';
// Layout.astro reads this client-side-visible flag to show/hide "+ New
// article". Derived from SSR so it's the one env var to set, not two.
process.env.PUBLIC_SSR = ssr ? '1' : '0';

// SSR is assumed self-hosted at the domain root; the static build defaults
// to the GitHub Pages project subpath. Override via .env (SITE=, BASE=) for
// a different target — e.g. a custom domain for either mode.
const site = process.env.SITE ?? (ssr ? undefined : 'https://sola-ryu.github.io');
const rawBase = process.env.BASE ?? (ssr ? '/' : '/solapedia/');
const base = rawBase.endsWith('/') ? rawBase : `${rawBase}/`;

// LLM generations sometimes cite a real Wikipedia article instead of linking
// internally. Rewrite those to our own /wiki/<title> so they resolve inside
// Solapedia (generating the article on demand in SSR) rather than leaving
// the site. Kept in sync with the copy in src/pages-ssr/wiki-slug.astro.
function wikipediaToInternalHref(href) {
	const match = href.match(/^https?:\/\/[a-z0-9-]+\.wikipedia\.org\/wiki\/([^?#]+)/i);
	return match ? `/wiki/${decodeURIComponent(match[1])}` : null;
}

/**
 * Rewrites root-relative hrefs in article content (e.g. `/wiki/foo`, written
 * by hand or generated by an LLM) to be relative to `base`, so links work
 * when the site is deployed under a subpath (e.g. GitHub Pages). Also makes
 * external http(s) links open in a new tab with rel="noopener noreferrer".
 */
function processLinks() {
	return (tree) => {
		function walk(node) {
			if (node.tagName === 'a' && typeof node.properties?.href === 'string') {
				const href = wikipediaToInternalHref(node.properties.href) ?? node.properties.href;
				if (href.startsWith('/') && !href.startsWith('//')) {
					node.properties.href = base.replace(/\/$/, '') + href;
				} else if (/^https?:\/\//i.test(href)) {
					node.properties.href = href;
					node.properties.target = '_blank';
					node.properties.rel = 'noopener noreferrer';
				}
			}
			node.children?.forEach(walk);
		}
		walk(tree);
	};
}

export default defineConfig({
	site,
	base,
	adapter: ssr ? node({ mode: 'standalone' }) : undefined,
	markdown: {
		processor: unified({ rehypePlugins: [processLinks] }),
	},
	integrations: ssr
		? [
				{
					name: 'solapedia-ssr-routes',
					hooks: {
						'astro:config:setup': ({ injectRoute }) => {
							injectRoute({
								pattern: '/new',
								entrypoint: './src/pages-ssr/new.astro',
							});
							injectRoute({
								pattern: '/404',
								entrypoint: './src/pages-ssr/404.astro',
							});
							// A rest param, not `[slug]`: an identical pattern to the static
							// src/pages/wiki/[slug].astro route silently loses the collision
							// (only one survives in the manifest) instead of coexisting as a
							// fallback. `[...slug]` is a distinct pattern Astro can fall back
							// to once the static route's own prerendered paths don't match.
							injectRoute({
								pattern: '/wiki/[...slug]',
								entrypoint: './src/pages-ssr/wiki-slug.astro',
							});
						},
					},
				},
			]
		: [],
});
